### PR TITLE
docs(packaging): add docs to packages

### PR DESCRIPTION
**Pull request by benlangfeld**
Allows installations to serve their own documentation relevant to the exact version installed without any external resources.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 85642f8f8ada0bac68bca16fae9f82bb8cf5a17f
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/benlangfeld/QueueFlex/blob/master/CONTRIBUTING.md#pull-requests

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 2f788fc709a41f559bf26e6fd13812ba9a2ae7fb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/benlangfeld/QueueFlex/blob/master/CONTRIBUTING.md#pull-requests

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 2f788fc709a41f559bf26e6fd13812ba9a2ae7fb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/benlangfeld/QueueFlex/blob/master/CONTRIBUTING.md#pull-requests

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 2f788fc709a41f559bf26e6fd13812ba9a2ae7fb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/benlangfeld/QueueFlex/blob/master/CONTRIBUTING.md#pull-requests

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 2f788fc709a41f559bf26e6fd13812ba9a2ae7fb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: da842bacf69e055cf9082a3257ad65dd049b6f51
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/benlangfeld/QueueFlex/blob/master/CONTRIBUTING.md#pull-requests

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 2f788fc709a41f559bf26e6fd13812ba9a2ae7fb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: da842bacf69e055cf9082a3257ad65dd049b6f51
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/benlangfeld/QueueFlex/blob/master/CONTRIBUTING.md#pull-requests

---
This message was auto-generated by https://gitcop.com

**Comment by benlangfeld** [comment]
LGTM

**Pull request merged**
